"""indicators table

Revision ID: 0a2cc2461e07
Revises: a1e2aa0bec8a
Create Date: 2026-07-14 07:03:48.716157

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '0a2cc2461e07'
down_revision = 'a1e2aa0bec8a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('indicators',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('default_params', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_indicators_name'), 'indicators', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_indicators_name'), table_name='indicators')
    op.drop_table('indicators')
    # ### end Alembic commands ###
