"""trades table

Revision ID: 2e2c7d5ffc02
Revises: d8bf8cdc25d0
Create Date: 2026-07-10 20:25:57.750105

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '2e2c7d5ffc02'
down_revision = 'd8bf8cdc25d0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trades',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('side', sa.String(length=4), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('open_price', sa.Float(), nullable=False),
    sa.Column('open_time', sa.Integer(), nullable=False),
    sa.Column('sl', sa.Float(), nullable=True),
    sa.Column('tp', sa.Float(), nullable=True),
    sa.Column('spread_points_at_entry', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(length=255), nullable=False),
    sa.Column('strategy_version', sa.String(length=64), nullable=True),
    sa.Column('skill', sa.String(length=64), nullable=True),
    sa.Column('close_price', sa.Float(), nullable=True),
    sa.Column('close_time', sa.Integer(), nullable=True),
    sa.Column('profit', sa.Float(), nullable=True),
    sa.Column('m5_entry_snapshot', sa.JSON(), nullable=False),
    sa.Column('h1_entry_snapshot', sa.JSON(), nullable=False),
    sa.Column('m5_exit_snapshot', sa.JSON(), nullable=False),
    sa.Column('h1_exit_snapshot', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trades_symbol'), 'trades', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trades_symbol'), table_name='trades')
    op.drop_table('trades')
    # ### end Alembic commands ###
