"""ai task provider override table

Revision ID: 369b56f79a5d
Revises: 9c1f2a7e5b3d
Create Date: 2026-07-12 13:48:15.707177

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '369b56f79a5d'
down_revision = '9c1f2a7e5b3d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_task_provider_override',
    sa.Column('task', sa.String(length=32), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('updated_at', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('task')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ai_task_provider_override')
    # ### end Alembic commands ###
