"""initial schema

Revision ID: 4f5754e79bce
Revises: 
Create Date: 2026-07-10 12:37:07.958823

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '4f5754e79bce'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
