"""ai drafts and strategy versions tables

Revision ID: 7879d431d4eb
Revises: 2e2c7d5ffc02
Create Date: 2026-07-11 09:32:14.682190

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '7879d431d4eb'
down_revision = '2e2c7d5ffc02'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_drafts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_filename', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('extracted_spec', sa.JSON(), nullable=False),
    sa.Column('edited_spec', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('strategy_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('parent_version_id', sa.String(length=36), nullable=True),
    sa.Column('draft_id', sa.String(length=36), nullable=True),
    sa.Column('spec', sa.JSON(), nullable=True),
    sa.Column('backtest_report_id', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategy_versions_name'), 'strategy_versions', ['name'], unique=False)
    op.create_index(op.f('ix_strategy_versions_status'), 'strategy_versions', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_strategy_versions_status'), table_name='strategy_versions')
    op.drop_index(op.f('ix_strategy_versions_name'), table_name='strategy_versions')
    op.drop_table('strategy_versions')
    op.drop_table('ai_drafts')
    # ### end Alembic commands ###
