"""add paused flag to strategy versions

Revision ID: 9ae65ef97d1d
Revises: 369b56f79a5d
Create Date: 2026-07-13 05:22:38.501494

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '9ae65ef97d1d'
down_revision = '369b56f79a5d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('strategy_versions', sa.Column('paused', sa.Boolean(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('strategy_versions', 'paused')
    # ### end Alembic commands ###
