"""ai analysis reports and refinement proposals tables

Revision ID: 9c1f2a7e5b3d
Revises: 7879d431d4eb
Create Date: 2026-07-11 10:15:00.000000

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '9c1f2a7e5b3d'
down_revision = '7879d431d4eb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_analysis_reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('strategy_name', sa.String(length=128), nullable=False),
    sa.Column('base_version_id', sa.String(length=36), nullable=False),
    sa.Column('trade_ids', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('win_rate', sa.Float(), nullable=False),
    sa.Column('avg_r', sa.Float(), nullable=False),
    sa.Column('common_failure_pattern', sa.Text(), nullable=False),
    sa.Column('session_or_news_correlation', sa.Text(), nullable=False),
    sa.Column('verdict', sa.String(length=32), nullable=False),
    sa.Column('raw_llm_response', sa.Text(), nullable=False),
    sa.Column('proposal_id', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_analysis_reports_symbol'), 'ai_analysis_reports', ['symbol'], unique=False)
    op.create_index(op.f('ix_ai_analysis_reports_strategy_name'), 'ai_analysis_reports', ['strategy_name'], unique=False)
    op.create_table('ai_refinement_proposals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('report_id', sa.String(length=36), nullable=False),
    sa.Column('strategy_name', sa.String(length=128), nullable=False),
    sa.Column('base_version_id', sa.String(length=36), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('proposed_code', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('sandbox_errors', sa.JSON(), nullable=False),
    sa.Column('new_version_id', sa.String(length=36), nullable=True),
    sa.Column('baseline_backtest_report_id', sa.String(length=64), nullable=True),
    sa.Column('candidate_backtest_report_id', sa.String(length=64), nullable=True),
    sa.Column('improvement_pct', sa.Float(), nullable=True),
    sa.Column('applied_mode', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_refinement_proposals_report_id'), 'ai_refinement_proposals', ['report_id'], unique=False)
    op.create_index(op.f('ix_ai_refinement_proposals_strategy_name'), 'ai_refinement_proposals', ['strategy_name'], unique=False)
    op.create_index(op.f('ix_ai_refinement_proposals_status'), 'ai_refinement_proposals', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_refinement_proposals_status'), table_name='ai_refinement_proposals')
    op.drop_index(op.f('ix_ai_refinement_proposals_strategy_name'), table_name='ai_refinement_proposals')
    op.drop_index(op.f('ix_ai_refinement_proposals_report_id'), table_name='ai_refinement_proposals')
    op.drop_table('ai_refinement_proposals')
    op.drop_index(op.f('ix_ai_analysis_reports_strategy_name'), table_name='ai_analysis_reports')
    op.drop_index(op.f('ix_ai_analysis_reports_symbol'), table_name='ai_analysis_reports')
    op.drop_table('ai_analysis_reports')
    # ### end Alembic commands ###
