"""candles table

Revision ID: d8bf8cdc25d0
Revises: 4f5754e79bce
Create Date: 2026-07-10 13:28:17.921972

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'd8bf8cdc25d0'
down_revision = '4f5754e79bce'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candles',
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('timeframe', sa.String(length=4), nullable=False),
    sa.Column('time', sa.BigInteger(), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('tick_volume', sa.Integer(), nullable=False),
    sa.Column('spread_points', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('symbol', 'timeframe', 'time')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('candles')
    # ### end Alembic commands ###
